// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';
import type * as prismicT from '@prismicio/types';

type Simplify<T> = {
	[KeyType in keyof T]: T[KeyType];
};
/** Content for Announcement Banner documents */
interface AnnouncementBannerDocumentData {
	/**
	 * announcement field in *Announcement Banner*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Same-day delivery now available!
	 * - **API ID Path**: announcement_banner.announcement
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
	 *
	 */
	announcement: prismicT.RichTextField;
}
/**
 * Announcement Banner document from Prismic
 *
 * - **API ID**: `announcement_banner`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AnnouncementBannerDocument<Lang extends string = string> =
	prismicT.PrismicDocumentWithoutUID<
		Simplify<AnnouncementBannerDocumentData>,
		'announcement_banner',
		Lang
	>;
export type AllDocumentTypes = AnnouncementBannerDocument;
/**
 * Primary content in ImageBanner → Primary
 *
 */
interface ImageBannerSliceDefaultPrimary {
	/**
	 * Alt text field in *ImageBanner → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A very nice image.
	 * - **API ID Path**: image_banner.primary.alt_text
	 * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
	 *
	 */
	alt_text: prismicT.KeyTextField;
	/**
	 * Vertical padding field in *ImageBanner → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 2
	 * - **API ID Path**: image_banner.primary.vertical_padding
	 * - **Documentation**: https://prismic.io/docs/core-concepts/select
	 *
	 */
	vertical_padding: prismicT.SelectField<'2' | '4' | '8', 'filled'>;
	/**
	 * Banner image field in *ImageBanner → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_banner.primary.banner_image
	 * - **Documentation**: https://prismic.io/docs/core-concepts/image
	 *
	 */
	banner_image: prismicT.ImageField<never>;
}
/**
 * Default variation for ImageBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ImageBanner`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageBannerSliceDefault = prismicT.SharedSliceVariation<
	'default',
	Simplify<ImageBannerSliceDefaultPrimary>,
	never
>;
/**
 * Slice variation for *ImageBanner*
 *
 */
type ImageBannerSliceVariation = ImageBannerSliceDefault;
/**
 * ImageBanner Shared Slice
 *
 * - **API ID**: `image_banner`
 * - **Description**: `ImageBanner`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageBannerSlice = prismicT.SharedSlice<
	'image_banner',
	ImageBannerSliceVariation
>;
declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig,
		): prismic.Client<AllDocumentTypes>;
	}
	namespace Content {
		export type {
			AnnouncementBannerDocumentData,
			AnnouncementBannerDocument,
			AllDocumentTypes,
			ImageBannerSliceDefaultPrimary,
			ImageBannerSliceDefault,
			ImageBannerSliceVariation,
			ImageBannerSlice,
		};
	}
}
